# syntax = edrevo/dockerfile-plus

FROM ubuntu:latest

INCLUDE+ ./scarab_memtrace/Dockerfile.common

# Set the user to memtrace
USER memtrace

# TODO: Install required packages

# Start your application
CMD ["/bin/bash"]
