# syntax = edrevo/dockerfile-plus

# choose a ubuntu version
FROM ubuntu:focal

INCLUDE+ ./common/Dockerfile.common

# TODO: Install required packages


# Switch to the dcuser user
USER dcuser

# Start your application
CMD ["/bin/bash"]
