# Install required packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 \
    python3-pip \
    git \
    sudo \
    wget \
    cmake \
    binutils \
    libunwind-dev \
    zlib1g-dev \
    libsnappy-dev \
    liblz4-dev \
    g++ \
    g++-multilib \
    doxygen \
    libconfig++-dev \
    vim
# Authorize SSH Host
RUN mkdir -p /root/.ssh && \
    chmod 700 /root/.ssh


# Workflow scripts are bind-mounted from the host checkout at run time rather
# than copied in; see the equivalent comment in Dockerfile.common. Several of
# the scripts this file used to COPY (run_scarab.sh, run_exp_using_descriptor.py,
# gather_cluster_results.py, ...) no longer exist under common/scripts, so these
# COPY lines had made this Dockerfile unbuildable.
# Must match INFRA_MOUNT_TARGET in scripts/utilities.py (which is what actually
# gets passed to `docker run --mount`) and the ${INFRA_HOME:-...} default in
# common/scripts/root_entrypoint.sh.
ENV INFRA_HOME="/scarab_infra"
RUN mkdir -p $INFRA_HOME

RUN mkdir -p /simpoint_traces
ENV trace_home="/simpoint_traces"

# Set the working directory
ENV tmpdir="/tmp_home"
RUN mkdir -p $tmpdir && chmod -R 755 $tmpdir
WORKDIR $tmpdir

# DynamoRIO package
RUN cd $tmpdir && wget https://github.com/DynamoRIO/dynamorio/releases/download/release_10.0.0/DynamoRIO-Linux-10.0.0.tar.gz && tar -xzvf DynamoRIO-Linux-10.0.0.tar.gz
ENV DYNAMORIO_HOME=$tmpdir/DynamoRIO-Linux-10.0.0/
RUN chmod 777 $tmpdir/DynamoRIO-Linux-10.0.0/lib64/release/libdynamorio.so

# Build fingerprint client
COPY fingerprint_src $tmpdir/fingerprint_src/
RUN mkdir $tmpdir/fingerprint_src/build && \
    cd $tmpdir/fingerprint_src/build && \
    cmake -DDynamoRIO_DIR=$DYNAMORIO_HOME/cmake .. && \
    make && \
    cp ./libfpg.so $tmpdir/libfpg.so

# Install Scarab dependencies
RUN cd $tmpdir && wget -nc https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.15-98253-gb56e429b1-gcc-linux.tar.gz && tar -xzvf pin-3.15-98253-gb56e429b1-gcc-linux.tar.gz

# Env to build Scarab
ENV PIN_ROOT $tmpdir/pin-3.15-98253-gb56e429b1-gcc-linux
ENV SCARAB_ENABLE_PT_MEMTRACE 1
ENV LD_LIBRARY_PATH $tmpdir/pin-3.15-98253-gb56e429b1-gcc-linux/extras/xed-intel64/lib
ENV LD_LIBRARY_PATH $tmpdir/pin-3.15-98253-gb56e429b1-gcc-linux/intel64/runtime/pincrt:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH $DYNAMORIO_HOME/lib64/release:$LD_LIBRARY_PATH

# Build SimPoint 3.2
# Reference:
# https://github.com/intel/pinplay-tools/blob/main/pinplay-scripts/PinPointsHome/Linux/bin/Makefile
RUN cd $tmpdir/ && \
    git clone https://github.com/kofyou/SimPoint.3.2.git && \
    make -C SimPoint.3.2 && \
    ln -s SimPoint.3.2/bin/simpoint ./simpoint

RUN cd $tmpdir/ && git clone https://github.com/litz-lab/scarab
RUN pip3 install -r $tmpdir/scarab/bin/requirements.txt

ENV DOCKER_BUILDKIT 1
ENV COMPOSE_DOCKER_CLI_BUILD 1
