# Install required packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 \
    python3-pip \
    python2 \
    git \
    sudo \
    wget \
    cmake \
    binutils \
    libunwind-dev \
    libboost-dev \
    zlib1g-dev \
    libsnappy-dev \
    liblz4-dev \
    g++-9 \
    g++-9-multilib \
    doxygen \
    libconfig++-dev \
    libboost-dev \
    vim \
    bc \
    unzip \
    gosu

RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 1


# Copy workflow simpoint/no_simpoint script
COPY ./scripts/utilities.sh /usr/local/bin/utilities.sh
COPY ./common/scripts/run_clustering.sh /usr/local/bin/run_clustering.sh
COPY ./common/scripts/run_trace_post_processing.sh /usr/local/bin/run_trace_post_processing.sh

COPY ./common/scripts/run_simpoint_trace.sh /usr/local/bin/run_simpoint_trace.sh
COPY ./common/scripts/run_scarab.sh /usr/local/bin/run_scarab.sh
COPY ./common/scripts/run_scarab_allbench.sh /usr/local/bin/run_scarab_allbench.sh
COPY ./common/scripts/gather_fp_pieces.py /usr/local/bin/gather_fp_pieces.py
COPY ./common/scripts/run_exp_using_descriptor.py /usr/local/bin/run_exp_using_descriptor.py

COPY ./common/scripts/run_scarab_mode_4.sh /usr/local/bin/run_scarab_mode_4.sh
COPY ./common/scripts/run_scarab_mode_4_allbench.sh /usr/local/bin/run_scarab_mode_4_allbench.sh
COPY ./common/scripts/gather_cluster_results.py /usr/local/bin/gather_cluster_results.py
COPY ./common/scripts/gather_cluster_results_using_descriptor.py /usr/local/bin/gather_cluster_results_using_descriptor.py
COPY ./common/scripts/common_entrypoint.sh /usr/local/bin/common_entrypoint.sh

COPY ./common/scripts/run_single_simpoint.sh /usr/local/bin/run_single_simpoint.sh
RUN chmod +x /usr/local/bin/run_single_simpoint.sh

RUN mkdir -p /simpoint_traces

# Set the working directory
ENV tmpdir="/tmp_home"
RUN mkdir -p $tmpdir && chmod -R 755 $tmpdir
WORKDIR $tmpdir

# DynamoRIO package
RUN cd $tmpdir && wget https://github.com/DynamoRIO/dynamorio/releases/download/release_10.0.0/DynamoRIO-Linux-10.0.0.tar.gz && tar -xzvf DynamoRIO-Linux-10.0.0.tar.gz
ENV DYNAMORIO_HOME=$tmpdir/DynamoRIO-Linux-10.0.0/

# Build fingerprint client
COPY fingerprint_src $tmpdir/fingerprint_src/
RUN mkdir $tmpdir/fingerprint_src/build && \
    cd $tmpdir/fingerprint_src/build && \
    cmake -DDynamoRIO_DIR=$DYNAMORIO_HOME/cmake .. && \
    make && \
    cp ./libfpg.so $tmpdir/libfpg.so

# Install Scarab dependencies
RUN cd $tmpdir && wget -nc https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.15-98253-gb56e429b1-gcc-linux.tar.gz && tar -xzvf pin-3.15-98253-gb56e429b1-gcc-linux.tar.gz

# Env to build Scarab
ENV PIN_ROOT $tmpdir/pin-3.15-98253-gb56e429b1-gcc-linux
ENV SCARAB_ENABLE_PT_MEMTRACE 1
ENV LD_LIBRARY_PATH $tmpdir/pin-3.15-98253-gb56e429b1-gcc-linux/extras/xed-intel64/lib
ENV LD_LIBRARY_PATH $tmpdir/pin-3.15-98253-gb56e429b1-gcc-linux/intel64/runtime/pincrt:$LD_LIBRARY_PATH

# Build SimPoint 3.2
# Reference:
# https://github.com/intel/pinplay-tools/blob/main/pinplay-scripts/PinPointsHome/Linux/bin/Makefile
RUN cd $tmpdir/ && \
    git clone https://github.com/kofyou/SimPoint.3.2.git && \
    make -C SimPoint.3.2 && \
    ln -s SimPoint.3.2/bin/simpoint ./simpoint

ENV DOCKER_BUILDKIT 1
ENV COMPOSE_DOCKER_CLI_BUILD 1
